
const openingData=TABIA_POSITIONS,provenance=TABIA_PROVENANCE,pieces=TABIA_PIECES;let selected=0,ply=0,flipped=false,page=0;const pageSize=50;let filtered=openingData.map((r,i)=>i);
const el=id=>document.getElementById(id),de=s=>s.replace(/N/g,'S').replace(/B/g,'L').replace(/R/g,'T').replace(/Q/g,'D'),fmt=n=>n.toLocaleString('de-DE');
function rowTable(){el('positions').replaceChildren();for(const i of filtered.slice(page*pageSize,(page+1)*pageSize)){const r=openingData[i],tr=document.createElement('tr');tr.classList.toggle('selected',i===selected);const c0=document.createElement('td');c0.textContent=i+1;const btn=document.createElement('button');btn.textContent='Brett öffnen';btn.className='openboard';btn.onclick=()=>{selectOpening(i);el('player').scrollIntoView({behavior:'smooth',block:'start'})};c0.append(document.createElement('br'),btn);const c1=document.createElement('td');c1.className='num';c1.textContent=fmt(r.count);const c2=document.createElement('td');const title=document.createElement('div');title.textContent=r.eco+' · '+r.name;const moves=document.createElement('b');moves.textContent=de(r.moves);c2.append(title,moves);const c3=document.createElement('td');c3.className='results-col';c3.textContent=[r.results['1-0']||0,r.results['1/2-1/2']||0,r.results['0-1']||0].map(fmt).join(' / ');tr.append(c0,c1,c2,c3);el('positions').append(tr)}el('count').textContent=fmt(filtered.length)+' von '+fmt(openingData.length)+' Stellungen · nach Partienzahl absteigend';el('page-status').textContent='Seite '+(page+1)+' / '+Math.max(1,Math.ceil(filtered.length/pageSize));el('page-prev').disabled=page===0;el('page-next').disabled=(page+1)*pageSize>=filtered.length;}
function selectOpening(i){selected=i;ply=0;const r=openingData[i];el('opening-title').textContent=(i+1)+'. '+r.eco+' · '+r.name;el('opening-note').textContent=fmt(r.count)+' Partien · '+r.different_orders+' Zugfolgen · gezeigte Zugfolge '+fmt(r.sequence_count)+'-mal'+(r.named_at<6?' · Name des Vorläufers nach '+r.named_at+' Halbzügen':'');el('moves').replaceChildren();for(let n=0;n<3;n++){const line=document.createElement('div');line.className='moveline';const nr=document.createElement('span');nr.textContent=(n+1)+'.';line.append(nr);for(let j=0;j<2;j++){const k=n*2+j+1,b=document.createElement('button');b.textContent=de(r.steps[k-1]);b.dataset.ply=k;b.setAttribute('aria-label',(n+1)+'. '+(j?'Schwarz: ':'Weiß: ')+de(r.steps[k-1]));b.onclick=()=>{ply=k;render()};line.append(b)}el('moves').append(line)}render();rowTable()}
function render(){const r=openingData[selected],cells=[];for(const rank of r.states[ply].split('/'))for(const c of rank){if(/[1-8]/.test(c))cells.push(...Array(Number(c)).fill(''));else cells.push(c)}el('board').replaceChildren();for(let k=0;k<64;k++){const i=flipped?63-k:k,file=i%8,rank=8-Math.floor(i/8),name='abcdefgh'[file]+rank,square=document.createElement('div');square.className='square'+((file+rank)%2===0?' dark':'')+(r.last[ply].includes(name)?' last':'');if(cells[i])square.innerHTML=pieces[cells[i]];const coord=document.createElement('span');coord.className='coord';coord.textContent=name;square.append(coord);el('board').append(square)}el('board').setAttribute('aria-label','Schachbrett, '+(ply===0?'Grundstellung':'nach Halbzug '+ply+': '+de(r.steps[ply-1])));el('status').textContent='Halbzug '+ply+' / 6 · '+(ply%2?'Schwarz':'Weiß')+' am Zug';el('fen').textContent=r.fens[ply];el('first').disabled=el('prev').disabled=ply===0;el('next').disabled=el('end').disabled=ply===6;el('start').setAttribute('aria-pressed',String(ply===0));el('moves').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.ply)===ply)))}
el('first').onclick=el('start').onclick=()=>{ply=0;render()};el('prev').onclick=()=>{ply=Math.max(0,ply-1);render()};el('next').onclick=()=>{ply=Math.min(6,ply+1);render()};el('end').onclick=()=>{ply=6;render()};el('flip').onclick=()=>{flipped=!flipped;render()};document.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.key==='ArrowRight'){e.preventDefault();ply=Math.min(6,ply+1);render()}if(e.key==='ArrowLeft'){e.preventDefault();ply=Math.max(0,ply-1);render()}});
el('q').addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();filtered=openingData.map((r,i)=>i).filter(i=>{const r=openingData[i];return (r.name+' '+r.eco+' '+r.moves+' '+de(r.moves)).toLowerCase().includes(q)});page=0;rowTable()});el('page-prev').onclick=()=>{page--;rowTable()};el('page-next').onclick=()=>{page++;rowTable()};
function download(name,text,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
el('csv').onclick=()=>{const csv=[['Nr','Partien','ECO','Name','Zugfolge','FEN','Weisssiege','Remis','Schwarzsiege'],...openingData.map((r,i)=>[i+1,r.count,r.eco,r.name,r.moves,r.fen,r.results['1-0']||0,r.results['1/2-1/2']||0,r.results['0-1']||0])].map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\r\n');download('Lichess_Elite_Stellungen_ab20.csv','\uFEFF'+csv,'text/csv;charset=utf-8')};
el('pgn').onclick=()=>{const text=openingData.map((r,i)=>'[Event "Stellung '+(i+1)+' – '+r.count+' Partien"]\n[Site "Lichess Elite 2024-12 bis 2025-11"]\n[Date "????.??.??"]\n[Round "-"]\n[White "?"]\n[Black "?"]\n[Result "*"]\n\n'+r.moves+' *').join('\n\n');download('Lichess_Elite_Stellungen_ab20.pgn',text,'application/x-chess-pgn')};
el('json').onclick=()=>download('Lichess_Elite_Stellungen_ab20.json',JSON.stringify({provenance,positions:openingData},null,2),'application/json');selectOpening(0);
